### ISSUE TITLE
Traceback (most recent call last):   File "eva_interactive.py", line 479, in <module>     main()   File "eva_interactive.py", line 466, in main     model = setup_model_for_inference(args, tokenizer.vocab_size)   File "eva_interactive.py", line 155, in setup_model_for_inference     dist_init_required=False   File "/home/anthony/miniconda3/envs/p7/lib/python3.7/site-packages/deepspeed/__init__.py", line 136, in initialize     config_params=config_params)   File "/home/anthony/miniconda3/envs/p7/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 218, in __init__     self._configure_checkpointing(dist_init_required)   File "/home/anthony/miniconda3/envs/p7/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 556, in _configure_checkpointing     group=self.optimizer.dp_process_group) AttributeError: 'NoneType' object has no attribute 'dp_process_group'

### ISSUE THREAD

**Issue by anthonyyuan** [thu-coai/EVA#10]
Traceback (most recent call last):
  File "eva_interactive.py", line 479, in <module>
    main()
  File "eva_interactive.py", line 466, in main
    model = setup_model_for_inference(args, tokenizer.vocab_size)
  File "eva_interactive.py", line 155, in setup_model_for_inference
    dist_init_required=False
  File "/home/anthony/miniconda3/envs/p7/lib/python3.7/site-packages/deepspeed/__init__.py", line 136, in initialize
    config_params=config_params)
  File "/home/anthony/miniconda3/envs/p7/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 218, in __init__
    self._configure_checkpointing(dist_init_required)
  File "/home/anthony/miniconda3/envs/p7/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 556, in _configure_checkpointing
    group=self.optimizer.dp_process_group)
AttributeError: 'NoneType' object has no attribute 'dp_process_group'

**Comment by t1101675** [comment]
Hi, it seems that you didn't use the docker we provided (the version of the deepspeed is incorrect). We suggest to use our docker directly. If you would like to use your own deepspeed, please make sure the version is v0.3.9.
