### ISSUE TITLE
Run src/scripts/infer_enc_dec_interactive.sh

### ISSUE THREAD

**Issue by stonyhu** [thu-coai/EVA#12]
Hi @t1101675 , I encounter the following errors when running infer_enc_dec_interactive.sh. Is there something wrong with DeepSpeed version? My DeepSpeed version is 0.5.1, could you give some advise on this?

```
[2021-09-13 22:26:05,248] [INFO] [engine.py:197:__init__] DeepSpeed Flops Profiler Enabled: False
Traceback (most recent call last):
  File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 498, in <module>
    main()
  File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 485, in main
    model = setup_model_for_inference(args, tokenizer.vocab_size)
  **File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 168, in setup_model_for_inference
    model, optimizer, _, lr_scheduler = deepspeed.initialize(**
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/__init__.py", line 131, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 228, in __init__
    self._configure_checkpointing(dist_init_required)
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 572, in _configure_checkpointing
    group=self.optimizer.dp_process_group)
**AttributeError: 'NoneType' object has no attribute 'dp_process_group'**
Killing subprocess 4701
Traceback (most recent call last):
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 171, in <module>
    main()
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 161, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 139, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)

```

**Comment by t1101675** [comment]
We use DeepSpeed v0.3.9 and have some modifications to the package. We have just clarified this in the README. Thanks for your attention!

**Comment by stonyhu** [comment]
Thanks for the quick reply, I upgraded to DeepSpeed v0.3.9 and follow your instructions to replace `deepspeed/runtime/zero/stage1.py` with the `stage1.py` provided in your repo. Still encountered the follow errors:

```
building Enc-Dec model ...
 > number of parameters on model parallel rank 0: 2841040896
DeepSpeed is enabled.
[2021-09-14 13:31:34,828] [INFO] [logging.py:60:log_dist] [Rank 0] DeepSpeed info: version=0.3.9+unknown, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 498, in <module>
    main()
  File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 485, in main
    model = setup_model_for_inference(args, tokenizer.vocab_size)
  File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 168, in setup_model_for_inference
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/__init__.py", line 110, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 138, in __init__
    self._do_sanity_check()
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 469, in _do_sanity_check
    assert self._is_supported_optimizer(self.optimizer_name()), \
  File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 464, in _is_supported_optimizer
    getattr(torch.optim, optimizer_name, None) is not None
TypeError: getattr(): attribute name must be string
```

**Comment by stonyhu** [comment]
@t1101675 Hi, I also follow your instructions to use your provided docker image to run the `bash scripts/infer_enc_dec_interactive.sh`. It turns out that no nvidia-driver is installed in your provided docker image. However, after installing nvidia-driver, I cannot reboot the docker image. Could you help on this?

**Comment by t1101675** [comment]
> Thanks for the quick reply, I downgrade to DeepSpeed v0.3.9 and follow your instructions to replace `deepspeed/runtime/zero/stage1.py` with the `stage1.py` provided in your repo. Still encountered the follow errors:
> 
> ```
> building Enc-Dec model ...
>  > number of parameters on model parallel rank 0: 2841040896
> DeepSpeed is enabled.
> [2021-09-14 13:31:34,828] [INFO] [logging.py:60:log_dist] [Rank 0] DeepSpeed info: version=0.3.9+unknown, git-hash=unknown, git-branch=unknown
> Traceback (most recent call last):
>   File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 498, in <module>
>     main()
>   File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 485, in main
>     model = setup_model_for_inference(args, tokenizer.vocab_size)
>   File "/mnt/huahu/projects/EVA/src/eva_interactive.py", line 168, in setup_model_for_inference
>     model, optimizer, _, lr_scheduler = deepspeed.initialize(
>   File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/__init__.py", line 110, in initialize
>     engine = DeepSpeedEngine(args=args,
>   File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 138, in __init__
>     self._do_sanity_check()
>   File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 469, in _do_sanity_check
>     assert self._is_supported_optimizer(self.optimizer_name()), \
>   File "/home/huahu/anaconda3/envs/eva/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 464, in _is_supported_optimizer
>     getattr(torch.optim, optimizer_name, None) is not None
> TypeError: getattr(): attribute name must be string
> ```

It seems that you have provided an `optimizer_name` but it's not a string or `None`. You can check whether you are using the `eva-origin/src/configs/deepspeed/eva_ds_config.json` we provided. If so, you can print the result of `self.optimizer_name()` and check its value.

**Comment by stonyhu** [comment]
Thanks @t1101675 for the kind help. My issue has been solved 👍
