### ISSUE TITLE
TCPStore(master_addr, master_port, world_size, start_daemon, timeout) ==>RuntimeError: connect() timed out.

### ISSUE THREAD

**Issue by lianlipen** [thu-coai/EVA#13]
1.在容器中执行了torch.cuda.device_count()，结果是1.

2.在容器中对宿主机ssh连接，也是通的。

报错信息：
[2021-09-15 08:47:29,228] [INFO] [launch.py:102:main] Setting CUDA_VISIBLE_DEVICES=0
Loading Model ...
WARNING: No training data specified
using world size: 1 and model-parallel size: 1 
 > using dynamic loss scaling
[2021-09-15 08:47:30,165] [INFO] [distributed.py:39:init_distributed] Initializing torch distributed with backend: nccl
Traceback (most recent call last):
  File "/mnt/src/eva_interactive.py", line 517, in <module>
    main()
  File "/mnt/src/eva_interactive.py", line 494, in main
    initialize_distributed(args)
  File "/mnt/src/eva_interactive.py", line 464, in initialize_distributed
    deepspeed.init_distributed()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/distributed.py", line 41, in init_distributed
    torch.distributed.init_process_group(backend=dist_backend)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: connect() timed out.

请问，目前的错误信息需要怎么解决了？谢谢指导！

**Comment by t1101675** [comment]
您好，我们这几天尝试复现这个错误，但是一直没有成功，感觉上仍然是 docker 配置的问题，导致torch.distributed无法使用。我们能想到的有两种解决方式：
1. 由于这个是 torch.distributed / deepspeed 的问题，可以到他们的仓库搜索是否有相似的 issue。
2. 尝试我们前几天更新的第二种配置方法，不用配置docker，只需要注意一下deepspeed的版本以及对这个包做一些简单的修改。应该也有人使用这种方法配置成功了。 https://github.com/thu-coai/EVA/issues/12

**Comment by lianlipen** [comment]
感谢您百忙之中的回复，我还想请教下:1.第一种方法中，docker有什么特殊的配置吗？因为我是从docker官网直接执行命令安装的，没有过特殊的配置。2.我还有一个疑问是，第一种方法中的配置文件有个参数是CKPT_PATH,这个参数配置的是模型的路径吗？谢谢指导！发自我的华为手机-------- 原始邮件 --------发件人： gyxbndsthu ***@***.***>日期： 2021年9月17日周五 上午9:31收件人： thu-coai/EVA ***@***.***>抄送： lianlipen ***@***.***>, Author ***@***.***>主    题： Re: [thu-coai/EVA] TCPStore(master_addr, master_port, world_size, start_daemon, timeout) ==>RuntimeError: connect() timed out. (#13)
您好，我们这几天尝试复现这个错误，但是一直没有成功，感觉上仍然是 docker 配置的问题，导致torch.distributed无法使用。我们能想到的有两种解决方式：
由于这个是 torch.distributed / deepspeed 的问题，可以到他们的仓库搜索是否有相似的 issue。尝试我们前几天更新的第二种配置方法，不用配置docker，只需要注意一下deepspeed的版本以及对这个包做一些简单的修改。应该也有人使用这种方法配置成功了。 #12

**Comment by t1101675** [comment]
1. 我们的 docker 配置了 GPU 以及分布式训练相关的功能，除此之外没有特殊的配置了。
2. CKPT_PATH 这个参数是模型的路径

**Comment by lianlipen** [comment]
谢谢回复！
在启动容器的时候，我们这里加了一些参数，因为如果不加参数的话，在docker中GPU无法使用。
sudo docker run --gpus all  -ti -v /home/EVA:/mnt gyxthu17/eva:1.2 /bin/bash，这个不会导致通讯失败吧？
谢谢指导！


| |
深蓝
|
|
***@***.***
|
签名由网易邮箱大师定制


On 09/17/2021 ***@***.***> wrote：

我们的 docker 配置了 GPU 以及分布式训练相关的功能，除此之外没有特殊的配置了。
CKPT_PATH 这个参数是模型的路径

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lianlipen** [comment]
您好,如果使用第二种方法的话。容器中的deepspeed包在哪里了？怎么替换python文件了。


| |
深蓝
|
|
***@***.***
|
签名由网易邮箱大师定制


On 09/17/2021 ***@***.***> wrote：
谢谢回复！
在启动容器的时候，我们这里加了一些参数，因为如果不加参数的话，在docker中GPU无法使用。
sudo docker run --gpus all  -ti -v /home/EVA:/mnt gyxthu17/eva:1.2 /bin/bash，这个不会导致通讯失败吧？
谢谢指导！


| |
深蓝
|
|
***@***.***
|
签名由网易邮箱大师定制


On 09/17/2021 ***@***.***> wrote：

我们的 docker 配置了 GPU 以及分布式训练相关的功能，除此之外没有特殊的配置了。
CKPT_PATH 这个参数是模型的路径

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by t1101675** [comment]
请仔细看readme，readme 里面有相应的配置方法。
<img width="873" alt="Screen Shot 2021-09-17 at 9 38 55 PM" src="https://user-images.githubusercontent.com/38183190/133792512-6e6d2797-f2d0-41a9-8fc9-aaed97de1c37.png">
