### ISSUE TITLE
torchrunn command not found 

### ISSUE THREAD

**Issue by jiangliqin** [thu-coai/EVA#21]
run the script in docker image:gyxthu17/eva:1.4,but the wrong is: torchrunn command not found

**Comment by xwwwwww** [comment]
try `python -m torch.distributed.launch` with torch 1.7.0

**Comment by jiangliqin** [comment]
your reply is so fast!! thanks, i got the answer

**Comment by t1101675** [comment]
Hi, thanks for pointing out this problem. We have updated the docker:`docker pull gyxthu17/eva:1.5`.

**Comment by jiangliqin** [comment]
use the gyxthu17/eva:1.5 image to run eva_finetune.sh got the wrong info, but the gyxthu17/eva:1.4 is ok!


` File "/mnt/src/eva_finetune.py", line 26, in <module>
  File "/mnt/src/eva_finetune.py", line 26, in <module>
        from apex.optimizers import FusedAdam as Adamfrom apex.optimizers import FusedAdam as Adam

  File "/opt/conda/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
  File "/opt/conda/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
        from . import ampfrom . import amp

  File "/opt/conda/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
        from .amp import init, half_function, float_function, promote_function,\from .amp import init, half_function, float_function, promote_function,\

  File "/opt/conda/lib/python3.8/site-packages/apex/amp/amp.py", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/amp.py", line 1, in <module>
        from . import compat, rnn_compat, utils, wrapfrom . import compat, rnn_compat, utils, wrap

  File "/opt/conda/lib/python3.8/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
        from . import utils, wrapfrom . import utils, wrap

  File "/opt/conda/lib/python3.8/site-packages/apex/amp/wrap.py", line 3, in <module>
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/wrap.py", line 3, in <module>
        from ._amp_state import _amp_statefrom ._amp_state import _amp_state

  File "/opt/conda/lib/python3.8/site-packages/apex/amp/_amp_state.py", line 14, in <module>
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/opt/conda/lib/python3.8/site-packages/torch/_six.py)
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/opt/conda/lib/python3.8/site-packages/torch/_six.py)
Traceback (most recent call last):
  File "/mnt/src/eva_finetune.py", line 26, in <module>
    from apex.optimizers import FusedAdam as Adam
  File "/opt/conda/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state`
