### ISSUE TITLE
ssh: Could not resolve hostname node-0: Name or service not known

### ISSUE THREAD

**Issue by basketballandlearn** [thu-coai/EVA#4]
ssh: Could not resolve hostname node-0: Name or service not known
Traceback (most recent call last):
  File "/usr/local/bin/deepspeed", line 6, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/launcher/runner.py", line 281, in main
    result = subprocess.check_output(hostname_cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ssh node-0 hostname -I']' returned non-zero exit status 255.

我看readme里面说：You also need to change node-0 ${WORKING_DIR}/src/configs/host_files/hostfile to the ssh node name (or IP) where you run distributed training，不是很懂要如何设置...... 还请大佬帮忙帮忙

**Comment by t1101675** [comment]
将 node-0 换成当前机器的 ip 地址就行，因为其内部是一个 ssh 操作，具体可以参考 deepspeed 的使用方式 https://github.com/microsoft/DeepSpeed
