### ISSUE TITLE
torch multiprocessing api failed

### ISSUE THREAD

**Issue by BaiMeiyingxue** [thu-coai/EVA#69]
Hi,
Great work!
I encounter the following error when I run  bash scripts/eva_inference_static.sh with 1 GPU:

ImportError: /home/zhangwenjuan/.cache/torch_extensions/py38_cu113/utils/utils.so: cannot open shared object file: No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 128439) of binary: /home/zhangwenjuan/anaconda3/envs/elmo/bin/python
Traceback (most recent call last):
  File "/home/zhangwenjuan/anaconda3/envs/elmo/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py FAILED

the log.txt only has :
Total train epochs 3 | Total train iters 10 | 

Any clue what is causing the error?

**Comment by BaiMeiyingxue** [comment]
with compiling PyTorch from source. warnings.warn(WRONG_COMPILER_WARNING.format(
Emitting ninja build file /home/zhangwenjuan/.cache/torch_extensions/py38_cu113/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: fatal: waitpid(128782): No child processes
Loading extension module utils...
Traceback (most recent call last):
  File "/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py", line 506, in <module>
    main()
  File "/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py", line 486, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, config, ds_config, args.do_train)
  File "/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py", line 139, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/__init__.py", line 110, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 198, in __init__
    util_ops = UtilsBuilder().load()
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 176, in load
    return self.jit_load(verbose)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 204, in jit_load
    op_module = load(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

**Comment by BaiMeiyingxue** [comment]
warnings.warn(WRONG_COMPILER_WARNING.format(
Emitting ninja build file /home/zhangwenjuan/.cache/torch_extensions/py38_cu113/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: fatal: waitpid(128782): No child processes
Loading extension module utils...
Traceback (most recent call last):
  File "/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py", line 506, in <module>
    main()
  File "/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py", line 486, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, config, ds_config, args.do_train)
  File "/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py", line 139, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/__init__.py", line 110, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 198, in __init__
    util_ops = UtilsBuilder().load()
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 176, in load
    return self.jit_load(verbose)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 204, in jit_load
    op_module = load(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/zhangwenjuan/.cache/torch_extensions/py38_cu113/utils/utils.so: cannot open shared object file: No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 128439) of binary: /home/zhangwenjuan/anaconda3/envs/elmo/bin/python
Traceback (most recent call last):
  File "/home/zhangwenjuan/anaconda3/envs/elmo/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhangwenjuan/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/zhangwenjuan/zhanghao/EVA-main/src/eva_finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-03_23:40:08
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 128439)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by t1101675** [comment]
```
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.
```

It seems that the error is caused by a mismatch between the compiler on your device and the compiler that builds the torch you installed?

**Comment by t1101675** [comment]
For the error `xxx/utils.so: cannot open shared object file: No such file or directory`. you can refer to #50 .

**Comment by BaiMeiyingxue** [comment]
> ```
> Your compiler (c++) is not compatible with the compiler Pytorch was
> built with for this platform, which is g++ on linux. Please
> use g++ to to compile your extension. Alternatively, you may
> compile PyTorch from source using c++, and then you can also use
> c++ to compile your extension.
> ```
> 
> It seems that the error is caused by a mismatch between the compiler on your device and the compiler that builds the torch you installed?
thanks for your reply
when i deploy the project to another server,it's ok. 

but when i run bash scripts/eva_finetune.sh with the kdconv dataset


arguments:
  model_config ................. /home/qianslab/EVA-main/src/configs/model/eva2.0_large_model_config.json
  model_parallel_size .......... 1
  fp16 ......................... True
  do_train ..................... True
  do_valid ..................... True
  do_eval ...................... True
  train_ratio .................. 1.0
  valid_ratio .................. 1
  test_ratio ................... 1
  batch_size ................... 16
  gradient_accumulation_steps .. 1
  train_iters .................. -1
  epochs ....................... 3
  weight_decay ................. 0.01
  checkpoint_activations ....... True
  checkpoint_num_layers ........ 1
  deepspeed_activation_checkpointing  True
  clip_grad .................... 1.0
  seed ......................... 422
  lr_decay_style ............... noam
  lr ........................... 0.0001
  warmup ....................... 0.01
  load ......................... /home/qianslab/EVA-main/eva2.0_large/
  load_optimizer_states ........ False
  load_lr_scheduler_states ..... False
  no_load_strict ............... True
  save ......................... /home/qianslab/EVA-main/results/finetune/
  save_interval ................ 500
  log_file ..................... /home/qianslab/EVA-main/results/finetune//log.txt
  log_interval ................. 100
  distributed_backend .......... nccl
  local_rank ................... 0
  eval_batch_size .............. None
  eval_interval ................ 500
  eval_generation .............. False
  temperature .................. 0.9
  top_p ........................ 0.9
  top_k ........................ 0
  max_generation_length ........ 128
  min_generation_length ........ 2
  num_beams .................... 1
  no_repeat_ngram_size ......... 3
  repetition_penalty ........... 1.2
  early_stopping ............... False
  length_penalty ............... 1.8
  rule_path .................... None
  data_path .................... /home/qianslab/EVA-main/data/kdconv
  cache_path ................... None
  tokenizer_path ............... /home/qianslab/EVA-main/bpe_dialog_new
  data_ext ..................... .txt
  num_workers .................. 2
  enc_seq_length ............... 128
  dec_seq_length ............... 128
  deepspeed .................... True
  deepspeed_config ............. /home/qianslab/EVA-main/src/configs/deepspeed/eva_ds_config.json
  deepscale .................... False
  deepscale_config ............. None
  deepspeed_mpi ................ False
  cuda ......................... True
  rank ......................... 0
  world_size ................... 1
  dynamic_loss_scale ........... True
[2022-11-04 20:15:06,926] [INFO] [checkpointing.py:248:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3140 and data parallel seed: 422
No cache, processing data

Loading data from /home/qianslab/EVA-main/data/kdconv/train.txt:   0%|          | 0/29700 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.804 seconds.
Prefix dict has been built successfully.
Loading data from /home/qianslab/EVA-main/data/kdconv/train.txt: 100%|██████████| 29700/29700 [00:36<00:00, 822.44it/s]
Cache path is None, no cache saved
Path: /home/qianslab/EVA-main/data/kdconv/train.txt | Ratio:1.0 | Max enc len: 128 | Max dec len: 128 | Data num: 29696
No cache, processing data
...
Loading data from /home/qianslab/EVA-main/data/kdconv/valid.txt: 100%|█████████▉| 8383/8421 [00:12<00:00, 728.54it/s]
Loading data from /home/qianslab/EVA-main/data/kdconv/valid.txt: 100%|██████████| 8421/8421 [00:12<00:00, 685.59it/s]

Cache path is None, no cache saved
Path: /home/qianslab/EVA-main/data/kdconv/valid.txt | Ratio:1 | Max enc len: 128 | Max dec len: 128 | Data num: 8417
Total train epochs 3 | Total train iters 5568 | 
building Enc-Dec model ...
 > number of parameters on model parallel rank 0: 967537664
Traceback (most recent call last):
  File "/home/qianslab/EVA-main/src/eva_finetune.py", line 506, in <module>
    main()
  File "/home/qianslab/EVA-main/src/eva_finetune.py", line 486, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, config, ds_config, args.do_train)
  File "/home/qianslab/EVA-main/src/eva_finetune.py", line 133, in setup_model_and_optimizer
    optimizer = get_optimizer(model, args)
  File "/home/qianslab/EVA-main/src/eva_finetune.py", line 88, in get_optimizer
    optimizer = Adam(param_groups,
  File "/home/qianslab/anaconda3/envs/elmo/lib/python3.8/site-packages/apex-0.1-py3.8.egg/apex/optimizers/fused_adam.py", line 80, in __init__
RuntimeError: apex.optimizers.FusedAdam requires cuda extensions
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 83703) of binary: /home/qianslab/anaconda3/envs/elmo/bin/python
Traceback (most recent call last):
  File "/home/qianslab/anaconda3/envs/elmo/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.1', 'console_scripts', 'torchrun')())
  File "/home/qianslab/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/qianslab/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/qianslab/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/qianslab/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/qianslab/anaconda3/envs/elmo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/qianslab/EVA-main/src/eva_finetune.py FAILED

**Comment by BaiMeiyingxue** [comment]
i use one GPU and i was wondering whether the error happens because the RAM was not enough during building the model?
if so, any suggestions to solve the error?

**Comment by t1101675** [comment]
You can use commands like `top` or `htop` to see the RAM usage. Our model does not need too much RAM.
