### ISSUE TITLE
请问，我在运行eva_finetune的时候出现了ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 58058) of binary:

### ISSUE THREAD

**Issue by zzzzhaozhao** [thu-coai/EVA#72]
运行eva_finetune出现如下错误

Traceback (most recent call last):
  File "/home/z/EVA/src/eva_finetune.py", line 506, in <module>
    main()
  File "/home/z/EVA/src/eva_finetune.py", line 486, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, config, ds_config, args.do_train)
  File "/home/z/EVA/src/eva_finetune.py", line 139, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/z/anaconda3/envs/pt1.11/lib/python3.9/site-packages/deepspeed/__init__.py", line 110, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/z/anaconda3/envs/pt1.11/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 198, in __init__
    util_ops = UtilsBuilder().load()
  File "/home/z/anaconda3/envs/pt1.11/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 176, in load
    return self.jit_load(verbose)
  File "/home/z/anaconda3/envs/pt1.11/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 204, in jit_load
    op_module = load(
  File "/home/z/anaconda3/envs/pt1.11/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/home/z/anaconda3/envs/pt1.11/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1382, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/z/anaconda3/envs/pt1.11/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1775, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /home/z/.cache/torch_extensions/py39_cu113/utils/utils.so: cannot open shared object file: No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 58058) of binary: /home/z/anaconda3/envs/pt1.11/bin/python

我想使用单卡来训练

**Comment by xwwwwww** [comment]
#50

请参考这个issue下的方法，生成`utils.so`文件

**Comment by zzzzhaozhao** [comment]
非常感谢您的回答，我已经成功解决了上面那个问题！但是我又遇到了
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)这个问题，服务器上是cuda11.8，但是我建立了cuda11.3的软连接，现在torch.version.cuda和nvcc --version一致，还是出错了，想请问您是否遇到过这个问题？

**Comment by zzzzhaozhao** [comment]
我的apex也是用cuda11.3编译的，之前用cuda11.6报错了，我就建立cuda11.3的软连接再安装的apex。会不会是服务器显卡的问题呢？服务器目前用的4090，可能是4090的cuda有问题？

**Comment by zzzzhaozhao** [comment]
了解，非常感谢您的回答！期待您早日开源huggingface的finetune~祝您一切顺利~
