### ISSUE TITLE
error occurred when i run eva_finetune.py

### ISSUE THREAD

**Issue by BaiMeiyingxue** [thu-coai/EVA#77]
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: fatal: waitpid(97011): No child processes
Loading extension module utils...
Traceback (most recent call last):
  File "/home/zhangwenjuan/zhanghao/EVA-main//src/eva_finetune.py", line 506, in <module>
    main()
  File "/home/zhangwenjuan/zhanghao/EVA-main//src/eva_finetune.py", line 486, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, config, ds_config, args.do_train)
  File "/home/zhangwenjuan/zhanghao/EVA-main//src/eva_finetune.py", line 139, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/deepspeed/__init__.py", line 110, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 198, in __init__
    util_ops = UtilsBuilder().load()
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 176, in load
    return self.jit_load(verbose)
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 204, in jit_load
    op_module = load(
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1317, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1699, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'utils'

i don't know how to fix it....  could you give me some suggestions?

**Comment by t1101675** [comment]
This issue may help #50 .

**Comment by BaiMeiyingxue** [comment]
> This issue may help #50 .

thanks for your reply!
i am confused... i can't understand the relationship between these errors

**Comment by t1101675** [comment]
Just try this https://github.com/thu-coai/EVA/issues/50#issuecomment-1216325642

**Comment by BaiMeiyingxue** [comment]
> Just try this [#50 (comment)](https://github.com/thu-coai/EVA/issues/50#issuecomment-1216325642)

thanks for your reply, sir!
